name: my_joints
description: "My Joints - A professional app for doctors to efficiently manage patient information, including medication history, DAS28-CRP, and SDAI scores, with seamless doctor consultation features."
publish_to: 'none' 

version: 1.0.0+2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.0
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.4
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  path: ^1.8.3
  provider: ^6.1.1
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1
  fl_chart: ^1.0.0
  file_picker: ^10.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/myjoints_logo512x512.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/myjoints_logo512x512.png"
